### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by nshen** [battlelinegames/wat-wasm#2]
![image](https://user-images.githubusercontent.com/181506/117617832-ade03300-b19f-11eb-8ae2-7603ed8ae255.png)

win 10 wsl

**Comment by battlelinegames** [comment]
What version of node are you using?

Thanks,
Rick

**Comment by nshen** [comment]
Hi Rick, I found this is a common ` CRLF / LF` problem, because after shebang the newline character is  `\r\n` instead of `\n` (unix style) , so my computer treat it as `node\r` + `\n` , I resaved your file as `LF`, and it fixed. thanks.

https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

**Comment by battlelinegames** [comment]
Thanks nshen,

I'll need to fix that in my code.  I appreciate you figuring it out for me :-)

Thanks again,
Rick

**Comment by battlelinegames** [comment]
Out of curiosity, did you grab it off github or use the npm package?  I'm just wondering because I was under the impression that npm made those fixes for you and I'm wondering if I am wrong about that.

thanks again,
Rick

**Comment by nshen** [comment]
> Out of curiosity, did you grab it off github or use the npm package? I'm just wondering because I was under the impression that npm made those fixes for you and I'm wondering if I am wrong about that.
> 
> thanks again,
> Rick

I was using a npm package,  `yarn global add wat-wasm` and I fixed it by finding my yarn global install folder and resaved that file.

**Comment by battlelinegames** [comment]
So it is an option on VS Code that I could have changed, except I thought that npm fixed the issue on upload for some reason.  I'm not sure where I heard that, but it's obviously wrong.  I'm going to need to change and fix that.

Thank you so much,
Rick

**Comment by battlelinegames** [comment]
So I fixed it using dos2unix and uploaded the new version to npm (version 1.0.28).  If you are willing to test the new version for me, I would greatly appreciate it.  If not, I appreciate that you made me aware of the issue in the first place.

Thanks again,
Rick

**Comment by nshen** [comment]
I tried 1.0.28,  `wat2wasm` works for me, but still display 1.0.26？

![image](https://user-images.githubusercontent.com/181506/117745358-e71ab080-b23c-11eb-8596-985658ff6180.png)

but `watwasm`  looks not working , watwasm is not defined

![image](https://user-images.githubusercontent.com/181506/117745456-192c1280-b23d-11eb-91ec-1093ab7a4612.png)

**Comment by battlelinegames** [comment]
There were a few problems with that.  I changed the output.  I don't remember having a watwasm script, I thought it was wat-wasm, but I copied wat-wasm to watwasm just to make sure.  The new version is 1.0.30.  I appreciate all of this help.   :-)

**Comment by nshen** [comment]
wat2wasm works,  but wat-wasm line 40
![image](https://user-images.githubusercontent.com/181506/117749800-f30a7080-b244-11eb-8e5b-7bcacd992d2c.png)

**Comment by battlelinegames** [comment]
Okay, hopefully I got it right this time. :-)

version 1.0.35

**Comment by battlelinegames** [comment]
I think it is working now.  No one has said anything since May 11
