### ISSUE TITLE
error: unexpected token get_local

### ISSUE THREAD

**Issue by tkoriginal** [battlelinegames/wat-wasm#5]
Just started a book and I'm really appreciating it! Thanks Rick.

I did run into an issue right off the bat with the wabt dependency. On install, it installs version 1.0.26 which will give you the following error without fail. I had to manually "downgrade" and fix the version to 1.0.25 in my global node_module fixed the issue. This is just incase someone just started the book! I am running MacOS. 1.0.25 is supposed to be the latest and 1.0.26 is currently pre-release but not sure why it was published. 

`Error: abort(Error: parseWat failed:
(module
  (func (export "AddInt")
  (param $value_1 i32) (param $value_2 i32)
  (result i32)
    get_local $value_1
    get_local $value_2
    i32.add
  )
)�:5:5: error: unexpected token get_local, expected ).
    get_local $value_1
    ^^^^^^^^^
(module
  (func (export "AddInt")
  (param $value_1 i32) (param $value_2 i32)
  (result i32)
    get_local $value_1
    get_local $value_2
    i32.add
  )
)�:6:5: error: unexpected token get_local.
    get_local $value_2
    ^^^^^^^^^
). Build with -s ASSERTIONS=1 for more info.
    at process.q (/usr/local/lib/node_modules/wat-wasm/node_modules/binaryen/index.js:54:175)
    at process.emit (node:events:402:35)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)`

**Comment by battlelinegames** [comment]
Thanks for letting me know.  So you think the problem is with the wabt dependency in wat-wasm?  Did you change the wabt version in the package.json?

Thanks again,
Rick

**Comment by tkoriginal** [comment]
Yes I went into my global node_modules and had to change it.

**Comment by battlelinegames** [comment]
I changed the package.json of wat-wasm to use the older version of the package.  I used 1.0.23 instead of 25 because that was the version I had tested it with the last time I used it.

Thanks for letting me know,
Rick
